MCU = atmega32u4
F_CPU = 16000000
ARCH = AVR8
F_USB = $(F_CPU)
OPT_DEFS += -DINTERRUPT_CONTROL_ENDPOINT
BOOTLOADER = caterina
OPT_DEFS += -DBOOTLOADER_SIZE=4096


BOOTMAGIC_ENABLE ?= no
MOUSEKEY_ENABLE ?= no
EXTRAKEY_ENABLE ?= no
CONSOLE_ENABLE ?= yes
COMMAND_ENABLE ?= no
SLEEP_LED_ENABLE ?= no
NKRO_ENABLE ?= yes
BACKLIGHT_ENABLE ?= no
AUDIO_ENABLE ?= no
RGBLIGHT_ENABLE ?= no
COMBO_ENABLE ?= no
TAP_DANCE_ENABLE ?= no
POINTING_DEVICE_ENABLE ?= yes
